import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';

export interface InvoicePdfData {
  tenant: {
    name: string;
    company_address: string | null;
    company_email: string | null;
    company_phone: string | null;
  };
  invoice: {
    id: number;
    invoice_number: string | null;
    date_issued: string;
    due_date: string;
    amount: number;
    notes: string | null;
  };
  job: {
    job_name: string;
    client_name: string;
  };
  paid: number;
  outstanding: number;
  status: string;
}

export async function generateInvoicePdf(data: InvoicePdfData): Promise<Uint8Array> {
  const pdfDoc = await PDFDocument.create();
  const page = pdfDoc.addPage([612, 792]);

  const helvetica = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const helveticaBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  const pageWidth = 612;
  const leftMargin = 50;
  const rightMargin = pageWidth - 50;
  const black = rgb(0, 0, 0);

  let y = 792 - 60;

  page.drawText(data.tenant.name || 'Hudson Business Solutions', {
    x: leftMargin,
    y,
    size: 20,
    font: helveticaBold,
    color: black,
  });
  y -= 22;

  if (data.tenant.company_address) {
    page.drawText(data.tenant.company_address, {
      x: leftMargin,
      y,
      size: 10,
      font: helvetica,
      color: black,
    });
    y -= 14;
  }

  if (data.tenant.company_email) {
    page.drawText(`Email: ${data.tenant.company_email}`, {
      x: leftMargin,
      y,
      size: 10,
      font: helvetica,
      color: black,
    });
    y -= 14;
  }

  if (data.tenant.company_phone) {
    page.drawText(`Phone: ${data.tenant.company_phone}`, {
      x: leftMargin,
      y,
      size: 10,
      font: helvetica,
      color: black,
    });
    y -= 14;
  }

  y -= 12;

  page.drawText('Invoice', {
    x: leftMargin,
    y,
    size: 14,
    font: helveticaBold,
    color: black,
  });
  y -= 24;

  const invLabel = data.invoice.invoice_number || `#${data.invoice.id}`;

  page.drawText(`Invoice: ${invLabel}`, {
    x: leftMargin,
    y,
    size: 12,
    font: helveticaBold,
    color: black,
  });

  const statusText = `Status: ${data.status}`;
  const statusWidth = helveticaBold.widthOfTextAtSize(statusText, 12);
  page.drawText(statusText, {
    x: rightMargin - statusWidth,
    y,
    size: 12,
    font: helveticaBold,
    color: black,
  });
  y -= 18;

  page.drawText(`Issue Date: ${data.invoice.date_issued}`, {
    x: leftMargin,
    y,
    size: 11,
    font: helvetica,
    color: black,
  });

  const dueText = `Due Date: ${data.invoice.due_date}`;
  const dueWidth = helvetica.widthOfTextAtSize(dueText, 11);
  page.drawText(dueText, {
    x: rightMargin - dueWidth,
    y,
    size: 11,
    font: helvetica,
    color: black,
  });
  y -= 18;

  page.drawText(`Client: ${data.job.client_name}`, {
    x: leftMargin,
    y,
    size: 11,
    font: helvetica,
    color: black,
  });
  y -= 18;

  page.drawText(`Job: ${data.job.job_name}`, {
    x: leftMargin,
    y,
    size: 11,
    font: helvetica,
    color: black,
  });
  y -= 25;

  page.drawLine({
    start: { x: leftMargin, y },
    end: { x: rightMargin, y },
    thickness: 1,
    color: black,
  });
  y -= 25;

  page.drawText('Summary', {
    x: leftMargin,
    y,
    size: 12,
    font: helveticaBold,
    color: black,
  });
  y -= 18;

  page.drawText(`Invoice Amount: $${formatCurrency(data.invoice.amount)}`, {
    x: leftMargin,
    y,
    size: 11,
    font: helvetica,
    color: black,
  });
  y -= 16;

  page.drawText(`Payments Received: $${formatCurrency(data.paid)}`, {
    x: leftMargin,
    y,
    size: 11,
    font: helvetica,
    color: black,
  });
  y -= 16;

  page.drawText(`Balance Due: $${formatCurrency(data.outstanding)}`, {
    x: leftMargin,
    y,
    size: 11,
    font: helveticaBold,
    color: black,
  });
  y -= 25;

  if (data.invoice.notes) {
    page.drawText('Notes', {
      x: leftMargin,
      y,
      size: 12,
      font: helveticaBold,
      color: black,
    });
    y -= 16;

    const text = String(data.invoice.notes);
    const maxCharsPerLine = 90;
    const lines = splitTextLines(text, maxCharsPerLine);
    const maxLines = 6;

    for (let i = 0; i < Math.min(lines.length, maxLines); i++) {
      page.drawText(lines[i], {
        x: leftMargin,
        y,
        size: 11,
        font: helvetica,
        color: black,
      });
      y -= 14;
    }
  }

  page.drawText(`Generated by ${data.tenant.name || 'Hudson Business Solutions'}`, {
    x: leftMargin,
    y: 40,
    size: 9,
    font: helvetica,
    color: black,
  });

  return pdfDoc.save();
}

function formatCurrency(value: number): string {
  return value.toLocaleString('en-US', {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  });
}

function splitTextLines(text: string, maxChars: number): string[] {
  const lines: string[] = [];
  for (let i = 0; i < text.length; i += maxChars) {
    lines.push(text.slice(i, i + maxChars));
  }
  return lines;
}
